baseURL = "https://grazielewest.github.io/"
title = "Tamires Trades"
theme = "stack"
defaultContentLanguage = "en"

[params]
  author = "Tamires"
  description = "Trading journal"
  mainSections = ["posts"]
  
  [params.dateFormat]
    published = "Jan 02, 2006"
    lastmod = "Jan 02, 2006"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Journal"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Strategy"
    url = "/strategy/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params.widgets]
  enabled = ["search", "archives", "tag-cloud"]